# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20170123_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
